version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./script.sh
    volumes:
      - .:/usr/src/striper/
    ports:
      - 8000:8000
    env_file:
      - .env
    container_name: web_app