# Generated by Django 5.0 on 2023-12-05 17:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_list',
            field=models.ManyToManyField(blank=True, default=[], related_name='items', to='product.item', verbose_name='Заказ'),
        ),
    ]
