# Generated by Django 5.0 on 2023-12-06 00:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_order_id_order_user_id_alter_order_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=11),
        ),
    ]
